image: python:3.10

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

pipelines:
  default:
    - step:
        name: Performance, style and tests
        script: # Modify the commands below to build your repository.
          - export PIP_CACHE_DIR="/opt/cache/pip"
          - apt-get update
          - apt-get upgrade -y
          - pip install pipenv 
          - pipenv sync --dev
          - export PYTHONPATH=src:$PYTHONPATH
          - pipenv run black --check .
          - pipenv run flake8
          - pipe: sonarsource/sonarcloud-scan:1.4.0
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6 